sudo: required
services:
    - docker

before_install:
    - docker build -t crownley/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true crownley/react-test npm test

after_success:
    - docker build -t crownley/multi-client ./client
    - docker build -t crownley/multi-nginx ./nginx
    - docker build -t crownley/multi-server ./server
    - docker build -t crownely/multi-worker ./worker

# Log in to the docker CLI
-echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
- docker push crownley/multi-client
- docker push crownley/multi-nginx
- docker push crownley/multi-server
- docker push crownley/multi-worker
